### ISSUE TITLE
User's feed not working?

### ISSUE THREAD

**Issue by khurshid-alam** [camporez/tpb2rss#3]
I try to create a feed with a user from  TPB. But it is giving empty feed. 

For example this feed `https://thepiratebay.cr/user/AhashareTeam/`

And rss feed:
`http://tpb.camporez.com/user/AhashareTeam/`

Which is empty!

**Comment by ianbrunelli** [comment]
Sorry for the late answer.

The script wasn't working at all since TPB was took down.

I just updated it today, so now the user feed should be fine.

**Comment by khurshid-alam** [comment]
@ianbrunelli I just tried it. It is still empty. The feed exists, but doesn't have any contents. `http://tpb.camporez.com/user/AhashareTeam/`

**Comment by ianbrunelli** [comment]
@khurshid-alam Yeah, apparently this user is not in `thepiratebay.se`¹, which is a different site from `thepiratebay.cr`. I don't recommend you to use the later, take a look [here](https://torrentfreak.com/fake-pirate-bay-lies-to-press-and-fakes-user-uploads-141215/).

1: https://thepiratebay.se/user/AhashareTeam/

**Comment by khurshid-alam** [comment]
Thanks. It seems feeds for users in `thepiratebay.se` are available are working well.
