### ISSUE TITLE
Fix "Installing On Openshift" Link

### ISSUE THREAD

**Issue by khurshid-alam** [camporez/tpb2rss#5]
The link leads to camporez.com/blog which is expired. Please fix it.

**Comment by ianbrunelli** [comment]
Thanks for reminding me of this. I have to change the links on the extension as well pointing to the new domain.

I'll do this in a few days. Meanwhile, you can find a copy of the tutorial [here](http://brunelli.me/thinny/blog/tpb2rss-openshift).

**Comment by khurshid-alam** [comment]
Thanks.

**Comment by ianbrunelli** [comment]
Closing this issue because it was fixed with f516de5d9ede2dcd6e9bdceff9308368b157c76c.

I have to update the tutorial, though.

**Comment by ianbrunelli** [comment]
@khurshid-alam , if you are using TPB2RSS on Openshift I highly recommend you to make a new install with version 2.0. Cheers.
