### ISSUE TITLE
Python 3.3 application documentation in the readme

### ISSUE THREAD

**Issue by 894-572** [camporez/tpb2rss#8]
The page has been deleted, Wayback Machine hasn't archived: https://web.archive.org/web/*/https://openshift.redhat.com/app/console/application_type/cart!python-3.3

**Comment by brunelli** [comment]
I've left TPB2RSS untouched for a long time, and since then much have changed both in The Pirate Bay and OpenShift.

Some weeks ago I made a commit to make the CLI work again, but the web interface will need some work.

In the mean time, I should ditch the OpenShift instructions and add a general "Installing in Linux" how-to.

**Comment by 894-572** [comment]
> In the mean time, I should ditch the OpenShift instructions and add a general "Installing in Linux" how-to.

I fully agree. If you're capable, please add Windows instructions as well.

**Comment by brunelli** [comment]
Hey, sorry for the late response.

I've setup a testing instance [on OpenShift](https://tpb2rss-tpb2rss.a3c1.starter-us-west-1.openshiftapps.com/) that you can use for as long as it's up. Please provide feedback in this issue.

I still have to update the docs and files in this repo, though, so I'm lefting this issue open.

**Comment by brunelli** [comment]
Openshift is [ending its free offer](https://blog.openshift.com/changes-to-openshift-online-starter-tier/). The link above will stop working soon.

As I'm not currenly using TPB2RSS and there are probably no active user, I'm closing this issue and archiving the project.

Anyone reading this can contact me [by email](https://github.com/camporez/tpb2rss/blob/master/tpb2rss.py#L12) regarding anything TPB2RSS-related.
