### ISSUE TITLE
Does tpb2rss support uploader feeds?

### ISSUE THREAD

**Issue by 894-572** [camporez/tpb2rss#9]
Is it possible to add a Pirate Bay account (`https://thepiratebay.org/user/`) as a feed source?

(I haven't yet managed to install the program, I'm asking if I should look for something else. I'm not aware of software to fetch RSS feed for a TPB account uploads)

**Comment by brunelli** [comment]
Yes, it does.

To test the program, install Python 3, then clone the repo and run, from the command line `python3 tpb2rss.py URL` (where URL is the URL you want to convert into a feed).

Are you planning to use it with a torrent client?

**Comment by 894-572** [comment]
> Are you planning to use it with a torrent client?

Not at the time, but I hope that's possible with all clients which support RSS.

**Comment by 894-572** [comment]
@brunelli For me the command `python3` isn't recognized while `python` is (Windows). It may be worthwhile to add this to the revamped readme.

However, I receive an error when running:
```
Traceback (most recent call last):
  File "tpb2rss.py", line 239, in <module>
    raise Exception("Failed to get feed\nHTTP status: %i %s" % (result.status.code, result.status.reason))
Exception: Failed to get feed
HTTP status: 200 OK
```

**Comment by 894-572** [comment]
I don't understand the output (some information related to the source URL removed):

```
<title>TPB2RSS: vonRicht</title>
                <link>https://thepiratebay.org/user/</link>
                <description>The Pirate Bay user feed for</description>
                <lastBuildDate>Fri, 12 Oct 2018 09:41:13 GMT</lastBuildDate>
                <language>en-us</language>
                <generator>TPB2RSS 2.0</generator>
                <docs>https://github.com/camporez/tpb2rss/</docs>
                <webMaster>ian@brunelli.me (Ian Brunelli)</webMaster>
```
...then followed by information about each torrent on the page. Where is the feed URL?

**Comment by brunelli** [comment]
This is the library responsible for feed generation, and it's working.

Together with Apache, mod_wsgi and the other files in this repo, you can create a web server to provide feed urls.

That's what the OpenShift tutorial was for, but after all the changes in their service I'll need to take a look at alternatives.

I'm closing this issue and will work towards fixing #8 next week. Additionally, I'll try to provide a hosted version of TPB2RSS.
